#!/bin/bash

#Generate Mysql root password.
root_pgsql_pass=$(openssl rand -hex 24)
debian_sys_maint_pgsql_pass=$(openssl rand -hex 24)

# Generate some passwords
cat > /root/.digitalocean_passwords <<EOM
DJANGO_USER=inventree
DJANGO_USER_PASSWORD=$(openssl rand -hex 16)
DJANGO_POSTGRESS_PASS=$(openssl rand -hex 16)
EOM

source /root/.digitalocean_passwords


# Configure password
sudo -u postgres psql -U postgres -d postgres -c "alter user postgres with password '${DJANGO_POSTGRESS_PASS}';"
sudo -u postgres psql -U postgres -d postgres -c "alter user ${DJANGO_USER} with password '${DJANGO_POSTGRESS_PASS}' ;"

# change config
sed -e "s/@inventree_password@/${DJANGO_POSTGRESS_PASS}/" -i "${SETTINGS_FILE}"

# create user
echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('$DJANGO_USER', 'temp@example.com', '$DJANGO_USER_PASSWORD')" | python3 "${PROJECT_DIR}/manage.py" shell

# Remove the ssh force logout command
sed -e '/Match User root/d' \
    -e '/.*ForceCommand.*droplet.*/d' \
    -i /etc/ssh/sshd_config

systemctl restart ssh
