#!/bin/bash -x
exec > >(tee /var/log/one_click_setup.log) 2>&1

# Generate some passwords
cat > /root/.digitalocean_passwords <<EOM
PROJECT_DIR=/home/inventree/src/InvenTree
SETTINGS_FILE=/etc/inventree/config.yaml
DJANGO_POSTGRESS_USER=inventree
DJANGO_POSTGRESS_PASS=$(openssl rand -hex 16)
DJANGO_POSTGRESS_PASS_ROOT=$(openssl rand -hex 16)
EOM
source /root/.digitalocean_passwords

# Configure postgres
setuid postgres psql -U postgres -d postgres -c "alter user postgres with password '${DJANGO_POSTGRESS_PASS_ROOT}';"
setuid postgres psql -U postgres -d postgres -c "alter user ${DJANGO_POSTGRESS_USER} with password '${DJANGO_POSTGRESS_PASS}' ;"

# Write DB config
sed -i s=USER: inventree=USER:\ ${DJANGO_POSTGRESS_USER}=g "${SETTINGS_FILE}"
sed -i s=PASSWORD: inventree_password=PASSWORD:\ \'${DJANGO_POSTGRESS_PASS}\'=g "${SETTINGS_FILE}"

# Run general updates
sudo apt update
sudo apt upgrade -y

# Add console
wget -qO- https://repos-droplet.digitalocean.com/install.sh | sudo bash

# Remove the ssh force logout command
sed -e '/Match User root/d' \
    -e '/.*ForceCommand.*droplet.*/d' \
    -i /etc/ssh/sshd_config

systemctl restart ssh
