#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

. /root/.digitalocean_passwords

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to MjMair's InvenTree Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

Access the Django admin site
    URL: http://${myip}/admin
    User: ${DJANGO_USER}
    Pass: ${DJANGO_USER_PASSWORD}

Django is configured to use Postgres as its database. Use the following
credentials to manage the database:
    Database: django
    User:     ${DJANGO_USER}
    Pass:     ${DJANGO_POSTGRESS_PASS}

Open your InvenTree Instance now: http://$myip

On the server:
  * The install follows InvenTree's bare metal install guide - use the user `ìnventree`
    for all actions and find your install in /home/inventree/src
  * The passwords are saved in /root/.digitalocean_password

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
