#!/bin/sh
#
# Configured as part of the DigitalOcean 1-Click Image build process

. /root/.digitalocean_passwords
export DJANGO_USER_PASSWORD=$(cat /etc/inventree/admin_password.txt)

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
********************************************************************************

Welcome to MjMair's InvenTree Droplet.
To keep this Droplet secure, the UFW firewall is enabled.
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

Access the admin site:
    URL: http://${myip}/admin
Default credentials:
    User: admin
    Pass: ${DJANGO_USER_PASSWORD}

Your instance is configured to use Postgres as its database. Use the following
credentials to manage the database:
    Database: inventree
    User:     ${DJANGO_POSTGRESS_USER}
    Pass:     ${DJANGO_POSTGRESS_PASS}

Open your InvenTree Instance now: http://$myip

On the server:
  * This install follows InvenTree's install guide - https://inventree.readthedocs.io/en/latest/start/installer/
  * The passwords are saved in /root/.digitalocean_password

********************************************************************************
To delete this message of the day: rm -rf $(readlink -f ${0})
EOF
